### ISSUE TITLE
Mac Framework

### ISSUE THREAD

**Issue by samhatchett** [renebigot/XlsxReaderWriter#14]
Thanks for the amazing work here. I'm testing this for use in a mac application - would you be interested in accepting a PR that includes a Mac Framework target?
https://github.com/samhatchett/XlsxReaderWriter/tree/mac-build
My mods end up affecting a good number of files in order to make it cross-platform, and I have not fully tested this for iOS, so I would have to ask for some help in making sure that nothing breaks for that build.

**Comment by renebigot** [comment]
Hi @samhatchett,
It's cool if you've done the job to support OS X.
PR are welcome !

**Comment by samhatchett** [comment]
awesome. this is a really useful library! PR #15
