### ISSUE TITLE
Where does BRANativeGraphicsGetImageFromContext come from?

### ISSUE THREAD

**Issue by iosre** [renebigot/XlsxReaderWriter#17]
<img width="599" alt="screen shot 2016-01-30 at 6 48 25 pm" src="https://cloud.githubusercontent.com/assets/6693854/12695223/192cd55e-c782-11e5-8a0a-3271e1d234fd.png">

**Comment by renebigot** [comment]
Hello, 
It's a macro defined in a header file for iOS and OS X (the definition is target dependent)
Are you compiling for OS X ? I'm currently using the trunk version on iOS without trouble.

**Comment by renebigot** [comment]
Hi @iosre ,
do you still have this error ?

**Comment by divnull** [comment]
I do. Create a new git clone. Open project on OS X. Compile for OS X.

Looks very much like code got updated with a changed header, but the header change was never committed. (Code contains BRANativeGraphicsGetImageFromContext, header does not contain that definition, but does contain BRANativeGraphicsGetImageFromCurrentImageContext.)

If you make the code use BRANativeGraphicsGetImageFromCurrentImageContext, it compiles, but there is another compile problem in BRAWorksheet.m.

**Comment by renebigot** [comment]
Sorry for the delay. It should be fixed now.
Tell me if it's ok (or not).

**Comment by divnull** [comment]
Header problem fixed, but compile error in BRAWorksheet.m remains:

.../XlsxReaderWriter/BRAWorksheet.m
.../XlsxReaderWriter/BRAWorksheet.m:523:79: Expected ')'
.../XlsxReaderWriter/BRAWorksheet.m:526:18: Use of undeclared identifier 'obj'
.../XlsxReaderWriter/BRAWorksheet.m:523:58: Incompatible block pointer types sending 'void (^)(BRACell *__strong)' to parameter of type 'void (^)(__strong id, NSUInteger, BOOL *)'

**Comment by renebigot** [comment]
Hi @divnull 
Can you check again please ?
Is your BRAWorksheet.m the same as the one in the repo.
I have no such error while compiling for iOS nor OS X.
I think that you've accidentally deleted the ')' at the end of the line 523 of BRAWorksheet.m
<img width="445" alt="badgood" src="https://cloud.githubusercontent.com/assets/1243762/13434463/3e587f74-dfd6-11e5-8efd-8635255099fe.png">

**Comment by divnull** [comment]
My code looks like the "good" version. Before I posted yesterday, I deleted everything and created a new clone to make sure.
![untitled-2](https://cloud.githubusercontent.com/assets/13994330/13435657/4fd530bc-dfa9-11e5-9789-5596e0425a44.png)

Looking further, I figured it out. I'm using the wrong version of XCode. The _Nonnull qualifier wasn't added until XCode 7. Sorry for the trouble.

**Comment by renebigot** [comment]
Oh, yes. I've forgotten that.
Happy that it now works.
I close this issue.
