### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by robocopklaus** [renebigot/XlsxReaderWriter#2]
CocoaPods (http://cocoapods.org) is a dependency manager for iOS / OS X projects. It's pretty easy to make your library compatible. You can take a look at https://guides.cocoapods.org/making/making-a-cocoapod.html

I already made the spec for your library as an example https://github.com/21stdigital/XlsxReaderWriter/blob/master/XlsxReaderWriter.podspec

Thanks for your great library

**Comment by renebigot** [comment]
I've got some problems with my commits labels but cocoapods should have been integrated. Could you please verify that everything is ok ?

Thanks.

**Comment by robocopklaus** [comment]
Cool, I'll take a look

**Comment by renebigot** [comment]
Hello robocopklaus,
Is CocoaPods running well with that file ?

**Comment by robocopklaus** [comment]
Hey, there a some issues with ZipArchive regarding CocoaPods. Unfortunately, they haven't fixed these issues the last time I checked. Since XlsxReaderWriter depends on it, I wasn't able to properly add support for CocoaPods :-(

**Comment by renebigot** [comment]
Fixed in 1.0.9. Thanx @robocopklaus
