### ISSUE TITLE
CocoaPods issue

### ISSUE THREAD

**Issue by wojczitsu** [renebigot/XlsxReaderWriter#22]
I've added XlsxReaderWriter to my Swift project with cocoa pods. 
Now if I add "import XlsxReaderWriter" I get error "Could not build Objective-C module 'XlsxReaderWriter'"

Any ideas what I've missed?

**Comment by wojczitsu** [comment]
It was caused by 
use_frameworks!
in my Podfile (I'm using Swift libraries and this one is only one in Obj-C).
To make it work, I had to replace #import "XMLDictionary.h" with @import XMLDictionary; in few classes

**Comment by renebigot** [comment]
It was a problem in your project ? Right ?

Should I close this issue ?

**Comment by Agm91** [comment]
Hi @renebigot, I have the exact same issue:
Could not build Objective-C module 'XlsxReaderWriter'.
I do not know if it is a dynamic framework or not, but if I remove the use_frameworks! of the podfile, I am not able to use many other libraries...
Could you please give me more info about how to use your library?
I have the pod and the Header, when adding the header, it says "'XlsxReaderWriter-swift-bridge.h' file not found", but when I want to import, mentioned error pops up.
Thank you in advance.
