### ISSUE TITLE
Linking for OS X project

### ISSUE THREAD

**Issue by steverowling** [renebigot/XlsxReaderWriter#24]
Following the instructions in the Read Me for linking to an OS X project, I get the following error when building the project:

    clang: error: no such file or directory: '/Users/steverowling/Library/Developer/Xcode/DerivedData/Metadata_Tagger-ewopyhauqwwrgqchyksrndhpnpwh/Build/Products/Debug/libXlsxReaderWriter.a'

If instead I use the following settings the project builds successfully:

* In the target **Build phases** insert **XlsxReaderWriter Mac (XlsxReaderWriter)** as a target dependency
* Add **XlsxReaderWriter.framework** and **libz.dylib** in **Link binary with Libraries**.

These settings allow the project to build correctly, but do not allow me to launch the resulting .app file directly from Finder without it crashing immediately due to not being able to find the XlsxReaderWriter.framework library.

If I also add **XlsxReaderWriter.framework** to the **Embed Frameworks** section of **Build Phases**, then the project builds correctly and can be launched and run successfully from it's .app bundle.

Note that I am not using cocoapods to link the framework to my project.

**Comment by renebigot** [comment]
I thank you very much for posting your question and answer here. I'll update the Readme soon for future users.

**Comment by joseprr87** [comment]
Thanks!
