### ISSUE TITLE
Problem with setting string content in Swift

### ISSUE THREAD

**Issue by wojczitsu** [renebigot/XlsxReaderWriter#26]
`worksheet.cellForCellReference("A1", shouldCreate: true).setStringValue("text")`
is not working. I'm saving file and trying to display cell content - it's empty.

**Comment by wojczitsu** [comment]
I found a reason.
I have used completely new and empty XLSX file as my template. There is a bug which is causing sharedStrings in BRAWorksheet to be nil with such empty xlsx file, and when sharedStrings is nil you can't add new string to cell.

Workaround:
Use as template .xlsx file with any string typed in.

**Comment by renebigot** [comment]
Hello !
That's right. The lib can't create a workbook from scratch for the same reason. 
I hope It will do in the future, unfortunately I have no time to develop this feature.
