### ISSUE TITLE
A cell values do not update dynamically if XlsxReaderWriter changes the values of its formula's dependencies

### ISSUE THREAD

**Issue by gistya** [renebigot/XlsxReaderWriter#28]
A cell values do not update dynamically if XlsxReaderWriter changes the values of its formula's dependencies. I realize that adding calculation and logic support for all of Excel's possible formulas would be a lot to ask, and individual programmers can put in what they need to the library on their own branch. 

If it is not noted in the README that formulas do not get calculated, then it would be nice to make that clear. If it is already stated there then nevermind.

**Comment by renebigot** [comment]
Hi @gistya.
Formulas is something really complex in the XLSX format. The lib can't compute value from formulas nor tell Excel that it must update the formula based cell content if there's a change in cells values.

The lib won't be updated to calculate formula in the future, unless someone has a lot of time to spend to implement this. (I've got no time for this)

**Comment by gistya** [comment]
No problem. It's a great and useful library, thanks for all your work. We are finding it extremely useful for letting non-programmers create data for unit tests!

**Comment by renebigot** [comment]
Happy to read it  :+1: 
Thanks to you to use XlsxReaderWriter
