### ISSUE TITLE
How can I get worksheet name or number of worksheet ?

### ISSUE THREAD

**Issue by TrongDucTran** [renebigot/XlsxReaderWriter#31]
Hi, I need to get worksheet name or number of worksheets in xlsx file, how can i do that ?

**Comment by TrongDucTran** [comment]
number of worksheets: spreadsheet.workbook.worksheets.count
How can I get worksheet name, please help me. Thank you

**Comment by renebigot** [comment]
The only way to get the worksheet name is by enumerating the sheets array (which contains BRASheet objects) in your workbook and comparing their identifier to your worksheet (BRAWorksheet) identifier. The name is inside the BRASheet object.

Complex ? Yes... It is related to the Open Office format architecture.

Have a look to the method 
`- (BRAWorksheet *)worksheetNamed:(NSString *)worksheetName;`

It may be helpful to understand how to get what you want.

If you just want to get a specific worksheet by its name, you have to use that method.
