### ISSUE TITLE
where is the file saving? if saveAs function is used?

### ISSUE THREAD

**Issue by trailburner** [renebigot/XlsxReaderWriter#37]
so I got this code here I'm using swift

let dirPath = NSSearchPathForDirectoriesInDomains(NSSearchPathDirectory.DocumentDirectory, NSSearchPathDomainMask.AllDomainsMask, true).first
        
        let xlsfile = "testtemp.xlsx"
        let fullPath = NSURL(fileURLWithPath: dirPath!).URLByAppendingPathComponent(xlsfile)
        spreadsheet.saveAs(fullPath.absoluteString)

I tested it with
let filemanager = NSFileManager.defaultManager()
        
        if filemanager.fileExistsAtPath(fullPath.absoluteString){
            print("file is there alright")
        }
        else{
            print("nada nothing")
        }

but it seems like it did not save

**Comment by renebigot** [comment]
Hi @trailburner .
saveAs do not support URL. Use `fullPath.path` instead.
