### ISSUE TITLE
set fill color problem

### ISSUE THREAD

**Issue by ODappsDev** [renebigot/XlsxReaderWriter#39]
in objective c cant get the fill color to work
any ideas?

**Comment by renebigot** [comment]
Any code example ?
I'm using cell fill in a some projects. It should work.

[How-to](https://github.com/renebigot/XlsxReaderWriter#get-cell-fill-as-a-uicolor)

**Comment by renebigot** [comment]
No response ? I suppose that it works now.

Closing
