### ISSUE TITLE
The app crashes when there is comments in the cell

### ISSUE THREAD

**Issue by karunakaran86** [renebigot/XlsxReaderWriter#4]
I tried to read a xlsx sheet which has comment into a cell . The app crashes with array out of bound exception when   trying to read the rels . Crashing in the below line.
  self.relationships = [[BRARelationships alloc] initWithContentsOfTarget:[self relationshipsTarget] inParentDirectory:self.cacheDirectory];

**Comment by renebigot** [comment]
Hello @karunakaran86, 

I've try to insert a comment in the "testWorkbook.xlsx" file from the test project.
Every tests failed. OK, I can replay the bug you've just discovered.

It seems that Excel has created a color indexed at index 81 (may be different in your case). Default indexed colors indexes should be lower than 65. No color 81 is defined by Excel in the XMLs: I don't understand why.

I'm working on it.

**Comment by renebigot** [comment]
Hi @karunakaran86,
this bug is corrected in the current version.
