### ISSUE TITLE
Extract data to xml or nsdictionnary

### ISSUE THREAD

**Issue by KevinJue** [renebigot/XlsxReaderWriter#42]
Hello, 

i'm seeing some function to get a NSDictionnary but it seem to be from xml so i try to find a solution in your work but ... 

did i miss something ? a method to extract directly in NSDictionnary ? or a method to extract xlsx to XML ? 

Cheers

**Comment by renebigot** [comment]
NSDictionary are used to read / write XML files.
XLSX are not converted to NSDictionary

**Comment by KevinJue** [comment]
okay, so you're solution can't be used for that.

just to try, do you try to do this ? or know solution for that ?

**Comment by renebigot** [comment]
I haven't try since XLSX files are not just some value in a table. You have to deal with shared strings, styles, merged cells and many other things. You could generate some NSDictionary for your needs, but there's few chances that your needs match with someone else needs
