### ISSUE TITLE
linking error 

### ISSUE THREAD

**Issue by sucharucrayonlabs** [renebigot/XlsxReaderWriter#5]
"_crc32", referenced from:
      _unzReadCurrentFile in unzip.o
      _zipWriteInFileInZip in zip.o
      _unzReadCurrentFile in libXlsxReaderWriter.a(unzip.o)
      _zipWriteInFileInZip in libXlsxReaderWriter.a(zip.o)
  "_deflate", referenced from:
      _zipWriteInFileInZip in zip.o
      _zipCloseFileInZipRaw64 in zip.o
      _zipWriteInFileInZip in libXlsxReaderWriter.a(zip.o)
      _zipCloseFileInZipRaw64 in libXlsxReaderWriter.a(zip.o)
  "_deflateEnd", referenced from:
      _zipCloseFileInZipRaw64 in zip.o
      _zipCloseFileInZipRaw64 in libXlsxReaderWriter.a(zip.o)
  "_deflateInit2_", referenced from:
      _zipOpenNewFileInZip4_64 in zip.o
      _zipOpenNewFileInZip4_64 in libXlsxReaderWriter.a(zip.o)
  "_get_crc_table", referenced from:
      _unzOpenCurrentFile3 in unzip.o
      _zipOpenNewFileInZip4_64 in zip.o
      _unzOpenCurrentFile3 in libXlsxReaderWriter.a(unzip.o)
      _zipOpenNewFileInZip4_64 in libXlsxReaderWriter.a(zip.o)
  "_inflate", referenced from:
      _unzReadCurrentFile in unzip.o
      _unzReadCurrentFile in libXlsxReaderWriter.a(unzip.o)
  "_inflateEnd", referenced from:
      _unzCloseCurrentFile in unzip.o
      _unzCloseCurrentFile in libXlsxReaderWriter.a(unzip.o)
  "_inflateInit2_", referenced from:
      _unzOpenCurrentFile3 in unzip.o
      _unzOpenCurrentFile3 in libXlsxReaderWriter.a(unzip.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by renebigot** [comment]
It seems like you have not add libZ.dylib to tour project dependencies

**Comment by renebigot** [comment]
Read the README.md file to know what to do.
