### ISSUE TITLE
After add image in sheet its not displaying

### ISSUE THREAD

**Issue by bigego28** [renebigot/XlsxReaderWriter#54]
On add image have some issue, which causing error while imaged added in sheet and not visible in right manner.

I have attach a screenshot of sheet with error. Please go through with it and let me know.

![screen shot 2016-10-07 at 4 06 09 pm](https://cloud.githubusercontent.com/assets/9594597/19187261/06f03b1a-8ca8-11e6-800e-9168922ec7ac.png)

**Comment by renebigot** [comment]
Unit tests prove it works. Should be a problem with your code or maybe same bug as #32

Have a look at `- (void)testAddTwoCellAnchoredImage`
