### ISSUE TITLE
XlsxReaderWriter : header file not found.

### ISSUE THREAD

**Issue by neerajcsa** [renebigot/XlsxReaderWriter#60]
Hi,
I am getting error BRAOfficeDocumentPackage.h file not found though i have followed all the steps which is written in ReadMe file.
I am using Xcode 8 and Objective C project.

**Comment by neerajcsa** [comment]
solved the issue.

**Comment by premkmrs87innovation** [comment]
Please let  know how did u solved this issue.. me too have the same issue..

**Comment by coderxdotwang** [comment]
Same issue with Xcode7.3.1 @neerajcsa Could you share the solution.

**Comment by avubotla** [comment]
Hi,
I am getting error 'BRAOfficeDocumentPackage.h' file not found. 

please let me know how to fix this issue??????
