### ISSUE TITLE
Chart and formula is not updated until file has been opened by Office Excel

### ISSUE THREAD

**Issue by Tim77277** [renebigot/XlsxReaderWriter#62]
So what i am trying to do is that I set up an excel template with formulas and charts, and then I insert some data. Finally, I want to view the file after I save it. Ideally, if I do this in the excel, the chart will change and formula will be updated in real time. However, when I use XlsxReaderWriter and use QLPreviewController (iOS) to preview the file, all inserted data are there but the chart and the formula is not updated. The chart will only be updated once I open the file with Office Excel itself. Does it has something to do with spreadsheet.save() function call?? 

Any suggestion will be appreciated

**Comment by renebigot** [comment]
Same as #61.

You need to write your own formula parser to do any update. It's far more complicated than just read / write XLSX file content.
