### ISSUE TITLE
Link to another workbook, save and open the file again

### ISSUE THREAD

**Issue by ench44** [renebigot/XlsxReaderWriter#64]
Open the new file saved in the / Document folder MS EXCEL prompts that the file is corrupt and can not read some data, I tried a number of ways:
When I create a new excel file, and create multiple sheets, then there is no link to the other workbook. Save the file no problem.
I think this error is probably due to my workbook contains a result of other links.

**Comment by ench44** [comment]
Very much hope to be answered

**Comment by renebigot** [comment]
This problem is not linked to what you're doing but to how OpenXML files are read by Excel.
I have to work on this, but I don't really have time for it :( 

Same as #27
