### ISSUE TITLE
how to use this library for swift3

### ISSUE THREAD

**Issue by MansoorJafari** [renebigot/XlsxReaderWriter#66]
Hi

after I create a header file and add this line #import "XlsxReaderWriter-swift-bridge.h" 

but dont work library in swift.
please help.

Thanks.

**Comment by charlymr** [comment]
I have am using the library in Swift3 no problems. i have a pull request 
https://github.com/renebigot/XlsxReaderWriter/pull/52

But @renebigot  did not look into it yet. Anyway, it works fine I tested it and using it.

then in you swift file you just do:
```import XlsxReaderWriter```

**Comment by MansoorJafari** [comment]
Thanks.
my problem is solve.

another question:

How to get sheetname in excel file?

**Comment by renebigot** [comment]
> How to get sheetname in excel file? 

Have a look at #31 for the sheet name.
