### ISSUE TITLE
How to create excel file

### ISSUE THREAD

**Issue by MansoorJafari** [renebigot/XlsxReaderWriter#67]
Hi
@renebigot 
How to create excel file in directory and save data in?

**Comment by renebigot** [comment]
You can't create an XLSX from scratch with this lib. You have to embed a minimal XLSX file in your project, open it, modify it and save it as a new file.

**Comment by JasmeetDev** [comment]
@renebigot I am unable to write to xlsx file saved in documents directory, and save it .

**Comment by KuDji** [comment]
@renebigot I am to - can't to write xlsx file, can't -  save it .
