### ISSUE TITLE
Error while loading content of file theme1.xml.

### ISSUE THREAD

**Issue by karunakaran86** [renebigot/XlsxReaderWriter#7]
When i write a data to the sheet for the first time it is working fine but for the second time i am getting below error. I am not getting this issue for all the sheet, Only for one particular sheet.  I am unable to identify what is in the excel sheet which is causing the error.  Please provide me your email so that I can share the excel sheet to you.

Error while loading content of file theme1.xml.

Error Domain=NSCocoaErrorDomain Code=260 "The operation couldn’t be completed. (Cocoa error 260.)" UserInfo=0x174660f80 {NSFilePath=/var/mobile/Containers/Data/Application/AAE85915-9D93-48E1-965B-8E2249AA149E/Library/Caches/fr.brae.spreadsheetdocument/test1-out.xlsx/xl/theme/theme1.xml, NSUnderlyingError=0x174243990 "The operation couldn’t be completed. No such file or directory"}

Thanks

**Comment by renebigot** [comment]
Hi,
Maybe the file won't be necessary. I'll do some tests today.

**Comment by renebigot** [comment]
Hello @karunakaran86,
you can send the file to rene[dot]bigot[at]brae[dot]fr

**Comment by renebigot** [comment]
Hi,
I've just pushed some bug fixes. This bug may have been corrected.

**Comment by riskoni** [comment]
Same here on OSX,Version is 2.0.1. Happens with every xlsx file

**Comment by renebigot** [comment]
Hello,
Could you please send me the code a xlsx files by mail please ?
Thanx

**Comment by renebigot** [comment]
the code "AND" the xlsx

**Comment by renebigot** [comment]
Any XLSX example to post here ?
