### ISSUE TITLE
Write cells content does not work

### ISSUE THREAD

**Issue by karunakaran86** [renebigot/XlsxReaderWriter#8]
I created simple excel sheet and trying to write data in to it. I have noticed that if there no border in the excel sheet , write to cell is not working. Only if there is border then it is working.

**Comment by renebigot** [comment]
Hi @karunakaran86 ,
In the sheets files, the only cells that are written by Excel are the cells that have a style or content set.
Try to use cellForCellReference:shouldCreate:

Example from README.MD : 
[[worksheet cellForCellReference:@"Y24" shouldCreate:YES] setStringValue:@"FOO / BAR"];

**Comment by pixsiro** [comment]
Hi,
for me it's the same: I cannot write an xlsx file (but I can read!!!).
I have installed XlsxReaderWriter as pod in my XCode app and i'm using method `cellForCellReference:shouldCreate:` to write.

**Comment by AmbroseSilveira** [comment]
Hi
Save your excel file in the documents directory , and then write to cells it will definitely work. It just means that you have to create copy of your excel file from assets and store it in different location and then perform the write functionality to it.
Thanks
