### ISSUE TITLE
Cannot write to cell.

### ISSUE THREAD

**Issue by AmbroseSilveira** [renebigot/XlsxReaderWriter#85]
Trying to write to a cell gives no result.

frstWorksheet.cell(forCellReference: "B2", shouldCreate: true).setStringValue("new value")

The above code does not work, or reflect the changes in the  #corresponding cells. 
Also, as found in the previous issues, adding a border to the cell also does not help. 

Please help. @renebigot

**Comment by vishwas513** [comment]
Who did you close it ? Did you manage to fix this ? I had the same problem.

**Comment by AmbroseSilveira** [comment]
@vishwas513 yes i got it fixed.

**Comment by JasmeetDev** [comment]
@AmbroseSilveira  Can you tell how you fixed the issue. I am stuck on the same.
